image: ubuntu1804

build: off

build_script:
  - python3 setup.py build

test_script:
  - python3 setup.py test

after_test:
  - python3 setup.py bdist_wheel bdist_egg

artifacts:
  - path: dist/*

cache:
  - ${HOME}/.eggs -> setup.py
